name: Bug report
description: Report a reproducible bug.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
    validations:
      required: true
